spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ams?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always